---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-cleanup-claim-2
  namespace: s3-cleanup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
